name: Build executables with PyInstaller

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller PySide6 mutagen

      - name: Download RSgain and FFmpeg (Linux)
        if: runner.os == 'Linux'
        run: |
          wget https://github.com/complexlogic/rsgain/releases/download/v3.6/rsgain-3.6-Linux.tar.xz
          tar xf rsgain-3.6-Linux.tar.xz
          # Find the rsgain binary and copy it to the current directory
          find . -type f -name rsgain -exec cp {} ./rsgain \;
          wget https://github.com/BtbN/FFmpeg-Builds/releases/latest/download/ffmpeg-n7.1-latest-linux64-gpl-7.1.tar.xz
          tar xf ffmpeg-n7.1-latest-linux64-gpl-7.1.tar.xz
          cp ffmpeg-n7.1-latest-linux64-gpl-7.1/bin/ffmpeg ./ffmpeg

      - name: Download RSgain and FFmpeg (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          curl -LO https://github.com/complexlogic/rsgain/releases/download/v3.6/rsgain-3.6-win64.zip
          powershell -Command "Expand-Archive -Path rsgain-3.6-win64.zip -DestinationPath ."
          if exist rsgain.exe (
            echo "rsgain.exe found in workspace."
          ) else (
            echo "rsgain.exe not found in workspace, searching in extracted files..."
            for %%f in (*.exe) do (
              if /I "%%~nxf"=="rsgain.exe" move "%%f" rsgain.exe
            )
          )
          if not exist rsgain.exe (
            echo "Error: rsgain.exe not found after extraction!"
            dir
            exit 1
          )
          curl -LO https://github.com/BtbN/FFmpeg-Builds/releases/latest/download/ffmpeg-n7.1-latest-win64-gpl-7.1.zip
          powershell -Command "Expand-Archive -Path ffmpeg-n7.1-latest-win64-gpl-7.1.zip -DestinationPath ffmpeg-win64"
          for /R ffmpeg-win64 %%i in (*.exe) do (
            if /I "%%~nxi"=="ffmpeg.exe" copy "%%i" ffmpeg.exe
          )

      - name: Download RSgain and FFmpeg (macOS)
        if: runner.os == 'macOS'
        run: |
          curl -LO https://github.com/complexlogic/rsgain/releases/download/v3.6/rsgain-3.6-macOS-x86_64.zip
          unzip rsgain-3.6-macOS-x86_64.zip
          mv rsgain-3.6-macOS-x86_64/rsgain ./rsgain
          brew install ffmpeg || true
          which ffmpeg && cp $(which ffmpeg) ./ffmpeg || echo "ffmpeg not found"

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --add-binary "rsgain:." --add-binary "ffmpeg:." museamp.pyw

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: museamp-${{ runner.os }}
          path: dist/*