name: Build MuseAmp Executables

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PySide6 mutagen pyinstaller

      - name: Download ffmpeg
        run: |
          curl -L -o ffmpeg.zip https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2025-06-13-13-43/ffmpeg-n7.1.1-22-g0f1fe3d153-winarm64-gpl-7.1.zip
          tar -xf ffmpeg.zip || powershell -c "Expand-Archive ffmpeg.zip ."
        shell: bash

      - name: Download rsgain
        run: |
          curl -L -o rsgain.zip https://github.com/complexlogic/rsgain/releases/download/v3.6/rsgain-3.6-win64.zip
          tar -xf rsgain.zip || powershell -c "Expand-Archive rsgain.zip ."
        shell: bash

      - name: Copy binaries to app folder
        run: |
          mkdir -p museamp_binaries
          # Find ffmpeg.exe and rsgain.exe and copy to museamp_binaries
          cp $(find . -iname ffmpeg.exe | head -n1) museamp_binaries/ffmpeg.exe
          cp $(find . -iname rsgain.exe | head -n1) museamp_binaries/rsgain.exe
        shell: bash

      - name: Build with PyInstaller
        run: |
          pyinstaller MuseAmp.pyw --name MuseAmpWindows --onefile --add-data "museamp_binaries;."
        env:
          PYTHONPATH: .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MuseAmpWindows
          path: dist/MuseAmpWindows.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PySide6 mutagen pyinstaller

      - name: Download ffmpeg
        run: |
          curl -L -o ffmpeg.tar.xz https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2025-06-13-13-43/ffmpeg-n7.1.1-22-g0f1fe3d153-linux64-gpl-7.1.tar.xz
          tar -xf ffmpeg.tar.xz
        shell: bash

      - name: Download rsgain
        run: |
          curl -L -o rsgain.tar.xz https://github.com/complexlogic/rsgain/releases/download/v3.6/rsgain-3.6-Linux.tar.xz
          tar -xf rsgain.tar.xz
        shell: bash

      - name: Copy binaries to app folder
        run: |
          mkdir -p museamp_binaries
          cp $(find . -type f -executable -name ffmpeg | head -n1) museamp_binaries/ffmpeg
          cp $(find . -type f -executable -name rsgain | head -n1) museamp_binaries/rsgain
        shell: bash

      - name: Build with PyInstaller
        run: |
          pyinstaller MuseAmp.pyw --name MuseAmpLinux --onefile --add-data "museamp_binaries:."
        env:
          PYTHONPATH: .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MuseAmpLinux
          path: dist/MuseAmpLinux

  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [x86_64, arm64]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PySide6 mutagen pyinstaller

      - name: Download ffmpeg
        run: |
          curl -L -o ffmpeg.zip https://evermeet.cx/ffmpeg/getrelease/zip
          unzip -o ffmpeg.zip
        shell: bash

      - name: Download rsgain
        run: |
          if [ "${{ matrix.arch }}" = "x86_64" ]; then
            curl -L -o rsgain.zip https://github.com/complexlogic/rsgain/releases/download/v3.6/rsgain-3.6-macOS-x86_64.zip
          else
            curl -L -o rsgain.zip https://github.com/complexlogic/rsgain/releases/download/v3.6/rsgain-3.6-macOS-arm64.zip
          fi
          unzip -o rsgain.zip
        shell: bash

      - name: Copy binaries to app folder
        run: |
          mkdir -p museamp_binaries
          cp $(find . -type f -name ffmpeg | head -n1) museamp_binaries/ffmpeg
          cp $(find . -type f -name rsgain | head -n1) museamp_binaries/rsgain
        shell: bash

      - name: Build with PyInstaller
        run: |
          pyinstaller MuseAmp.pyw --name MuseAmpMacOS --onefile --add-data "museamp_binaries:."
        env:
          PYTHONPATH: .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MuseAmpMacOS-${{ matrix.arch }}
          path: dist/MuseAmpMacOS

