name: Build MuseAmp Executables

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [published]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PySide6 mutagen pyinstaller

      - name: Setup FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v3
        with:
          ffmpeg-version: release

      - name: Download rsgain
        run: |
          curl -L -o rsgain.zip https://github.com/complexlogic/rsgain/releases/download/v3.6/rsgain-3.6-win64.zip
          tar -xf rsgain.zip || powershell -c "Expand-Archive rsgain.zip ."
        shell: bash

      - name: Copy binaries to app folder
        run: |
          mkdir -p museamp_binaries
          # FFmpeg is already in PATH from setup-ffmpeg action
          cp $(which ffmpeg) museamp_binaries/ffmpeg.exe
          cp $(find . -iname rsgain.exe | head -n1) museamp_binaries/rsgain.exe
        shell: bash

      - name: Build with PyInstaller
        run: |
          pyinstaller MuseAmp.pyw --name MuseAmpWindows --onefile --add-data "museamp_binaries;."
        env:
          PYTHONPATH: .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MuseAmpWindows
          path: dist/MuseAmpWindows.exe

      - name: Upload to GitHub Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: dist/MuseAmpWindows.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PySide6 mutagen pyinstaller

      - name: Setup FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v3
        with:
          ffmpeg-version: release

      - name: Download rsgain
        run: |
          curl -L -o rsgain.tar.xz https://github.com/complexlogic/rsgain/releases/download/v3.6/rsgain-3.6-Linux.tar.xz
          tar -xf rsgain.tar.xz
        shell: bash

      - name: Copy binaries to app folder
        run: |
          mkdir -p museamp_binaries
          # FFmpeg is already in PATH from setup-ffmpeg action
          cp $(which ffmpeg) museamp_binaries/ffmpeg
          cp $(find . -type f -executable -name rsgain | head -n1) museamp_binaries/rsgain
        shell: bash

      - name: Build with PyInstaller
        run: |
          pyinstaller MuseAmp.pyw --name MuseAmpLinux --onefile --add-data "museamp_binaries:."
        env:
          PYTHONPATH: .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MuseAmpLinux
          path: dist/MuseAmpLinux

      - name: Upload to GitHub Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: dist/MuseAmpLinux

  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [x86_64, arm64]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PySide6 mutagen pyinstaller

      - name: Download ffmpeg
        run: |
          curl -L -o ffmpeg.zip https://evermeet.cx/ffmpeg/getrelease/zip
          unzip -o ffmpeg.zip
        shell: bash

      - name: Download rsgain
        run: |
          if [ "${{ matrix.arch }}" = "x86_64" ]; then
            curl -L -o rsgain.zip https://github.com/complexlogic/rsgain/releases/download/v3.6/rsgain-3.6-macOS-x86_64.zip
          else
            curl -L -o rsgain.zip https://github.com/complexlogic/rsgain/releases/download/v3.6/rsgain-3.6-macOS-arm64.zip
          fi
          unzip -o rsgain.zip
        shell: bash

      - name: Copy binaries to app folder
        run: |
          mkdir -p museamp_binaries
          cp $(find . -type f -name ffmpeg | head -n1) museamp_binaries/ffmpeg
          cp $(find . -type f -name rsgain | head -n1) museamp_binaries/rsgain
        shell: bash

      - name: Build with PyInstaller
        run: |
          pyinstaller MuseAmp.pyw --name MuseAmpMacOS --onefile --add-data "museamp_binaries:."
        env:
          PYTHONPATH: .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MuseAmpMacOS-${{ matrix.arch }}
          path: dist/MuseAmpMacOS

      - name: Upload to GitHub Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: dist/MuseAmpMacOS